api_version = "2026-01"

[[extensions]]
type = "ui_extension"
name = "Tattoo Checkout"
uid = "bffb1f63-5705-ab9d-a4ea-64755e49b1231757a2f8"
handle = "artist-checkout"
description = "Facet and Form POS checkout tile"

# Pointing the Tile to our React file
[[extensions.targeting]]
module = "./src/index.tsx"
target = "pos.home.tile.render"

# Pointing the Modal to our React file
[[extensions.targeting]]
module = "./src/index.tsx"
target = "pos.home.modal.render"