# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4ca0bc28cbb2f206aad15dec373de43"
name = "Tattoo Pricing"
application_url = "https://tattoopricing-wfcj3.ondigitalocean.app"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_locations,read_orders,write_orders,read_products,write_products,customer_read_draft_orders,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://tattoopricing-wfcj3.ondigitalocean.app/auth/callback" ]

[pos]
embedded = true
